### ISSUE TITLE
Could primervcf design Co-dominant markers?

### ISSUE THREAD

**Issue by XiaohuiZhang98** [Runsheng/primervcf#2]
Hi, Runsheng.
It's me again, in your latest version i could run vcf2del.py successfully. Here comes a new question.
In your primerdiffer package it describe like this :
`The C. nigoni genome is cn3_new.fa and C. briggsae genome is cb5.fa. To design C. briggsae unique primer, which would not amplify any region in C. nigoni, and amplify only one region in C. briggsae. The targeted region for C. briggsae is ChrX:12881200-15106660 (-pos or --position), one primer is designed for every 4kb interval (-i or --interval).`
It means primerdiffer design a dominant marker ( a region could amplified just in one materials ), and i found that same in primervcf.
But in many cases, it will be more useful to design a co-dominant marker with InDels called in the VCF file(We could amplify a region in two materials but their length is different and we can see 2 strips in hybrids F1 through Agarose electrophoresis).
The Walkthrough maybe design left-primer before the start of Deletion and right-primer after the end of Deletion showed in the del.bed we obtained from the vcf2del.bed.
Could you please process to achieve it ? I really appreciate it.
In addition, i found that other kits with primer-design funtion(eg. VCF-Kit 、primerDesign), they both only use the Deletion sites rather than Insertion (also primervcf).But i think InDel can be classified into one category due to the sequence length variation,I wonder If it is because more complicated programming or other reasons?
Best wishes.
XiaoHui.

**Comment by Runsheng** [comment]
Hi Xiaohui,

Thank you for the question. These are good points for pipeline design. 

1. The primer can amplify both haplotypes with a length difference.  In our practice, the product size from this kind of primer is unstable using different Taq/PCR systems. For example, some PCR systems tend to amplify only the short haplotype. So the sample with 50% of the long haplotype could give you a pure band of the short haplotype. Using these primers for a specific site is possible if you use only a fixed PCR system.  And you need to draw a standard curve using pre-mixed samples with different compositions (0%, 25%, 50%... 75%, 100%) to ensure the usability of one primer. However, the primerdiffer and primervcf are used for genome-wide primer design, and we can not tolerate high false positives/negatives. 

2. Using insertion is harder than deletion in wet-lab practice. The issue is specificity check. The inserted sequences could be haplotype-specific repetitive sequences. The local specificity check will pass but the primer may not work well. 

Best,
Runsheng

**Comment by XiaohuiZhang98** [comment]
Really appreciate your reply! I have learned a lot from your answer.
Best,
Xiaohui
