### ISSUE TITLE
Function deprecated please use "design_primers" instead

### ISSUE THREAD

**Issue by Him22** [Runsheng/primervcf#3]
Dear Runsheng

I am facing the following issue in running the primervcf 

primerdesign_vcf.py -g cb5.fa -b QR25_del.bed --prefix QR25
mambaforge/lib/python3.10/site-packages/primer3/bindings.py:580: UserWarning: Function deprecated please use "design_primers" instead
  warnings.warn('Function deprecated please use "design_primers" instead')
Traceback (most recent call last):
  File "mambaforge/bin/primerdesign_vcf.py", line 76, in <module>
    flow_walk_deletion(
  File "mambaforge/lib/python3.10/site-packages/primervcf/primer_indel.py", line 141, in flow_walk_deletion
    primer_status = del_primer_check(del_single, db, ref_dict,
  File "mambaforge/lib/python3.10/site-packages/primervcf/primer_indel.py", line 101, in del_primer_check
    product_l = insilicon_pcr(left, right, db)
  File "mambaforge/lib/python3.10/site-packages/primerdiffer/primer_check.py", line 78, in insilicon_pcr
    blast_records_left = primer_blast(primer_left, db)
  File "mambaforge/lib/python3.10/site-packages/primerdiffer/primer_check.py", line 39, in primer_blast
    out, err = blastn_cline(stdin=query)
  File "mambaforge/lib/python3.10/site-packages/Bio/Application/__init__.py", line 574, in __call__
    raise ApplicationError(return_code, str(self), stdout_str, stderr_str)
Bio.Application.ApplicationError: Non-zero return code 2 from 'blastn -outfmt 5 -db cb5.fa -task blastn-short', message 'BLAST Database error: No alias or index file found for nucleotide database [cb5.fa] in search path [softwares/primervcf-0.1.0:::]'

Please help to resolve the issue
Thank you
Himanshu

**Comment by Runsheng** [comment]
Hi Himanshu,

Thank you for reporting the issue. There are too separate messages in your log. 
1. The "UserWarning: Function deprecated please use "design_primers" instead" should not affect your run result. The warning comes from primer3-py package, the new binding is design_primers instead of designPrimers, however, I need to keep it as it is to maintain the support for py38 and py39. 
2. The blast issue means the makeblastdb function did not run properly in your environment. I have added a double-check command in the new primervcf version (0.1.4). The issue should have been fixed. 

You can use `pip install primervcf` to update the module to 0.1.4. Or you can use the github repo for updates. 

Best regards,
Runsheng

**Comment by Him22** [comment]
Hi Runsheng,

Thank you for you response,
The problem was due to the python version installed in my system, I switched to py39 and it worked.

Best regards,
Himanshu
